#This file was automatically generated by the pretentious gem
require 'minitest_helper'
require "minitest/autorun"

class TestClass3Test < Minitest::Test
end

class TestClass3Scenario1 < TestClass3Test
  def setup
      another_object = TestClass1.new("test")
      var_2165630660 = {hello: "world", test: another_object, arr_1: [1, 2, 3, 4, 5, another_object], sub_hash: {yes: true, obj: another_object}}
      testclass1 = TestClass1.new(var_2165630660)
      testclass2 = TestClass2.new("This is message 2", nil)
      @fixture = TestClass3.new(testclass1, testclass2)
  end

  def test_current_expectation
    #TestClass3#show_messages  should return awesome!!!
    assert_equal "awesome!!!", @fixture.show_messages


  end
end

class TestClass3Scenario2 < TestClass3Test
  def setup
      another_object = TestClass1.new("test")
      var_2165630660 = {hello: "world", test: another_object, arr_1: [1, 2, 3, 4, 5, another_object], sub_hash: {yes: true, obj: another_object}}
      testclass1 = TestClass1.new(var_2165630660)
      testclass2 = TestClass2.new("This is message 2", nil)
      @fixture = TestClass3.new(testclass1, testclass2)
  end

  def test_current_expectation
    #TestClass3#show_messages  should return awesome!!!
    assert_equal "awesome!!!", @fixture.show_messages


  end
end

