#This file was automatically generated by the pretentious gem
require 'minitest_helper'
require "minitest/autorun"

class TestTestClass4 < Minitest::Test
end

class TestClass4Scenario1 < TestTestClass4
  def setup
      var_8 = nil
      var_2166614480 = Proc.new { 
            # Variable return values ... can't figure out what goes in here...
      }

      @fixture = TestClass4.new(&var_2166614480)
  end

  def test_current_expectation

  end
end

