#This file was automatically generated by the pretentious gem
require 'spec_helper'

RSpec.describe TestClass4 do

  context 'Scenario 1' do
    before do
      var_8 = nil
      var_2186933560 = Proc.new { 
            # Variable return values ... can't figure out what goes in here...
      }

      @fixture = TestClass4.new(&var_2186933560)
    end

    it 'should pass current expectations' do
    end
  end

end
