#This file was automatically generated by the pretentious gem
require 'spec_helper'

RSpec.describe TestClass4 do

  context 'Scenario 1' do
    before do

      var_2161428640 = Proc.new { 
            "test"
      }


      @fixture = TestClass4.new &var_2161428640

    end

    it 'should pass current expectations' do

    end
  end

end
