#This file was automatically generated by the pretentious gem
require 'spec_helper'

RSpec.describe TestClass3 do

  context 'Scenario 1' do
    before do
      var_2187209700 = TestClass1.new("test")
      var_2187229000 = {hello: "world", test: var_2187209700, arr_1: [1, 2, 3, 4, 5, var_2187209700], sub_hash: {yes: true, obj: var_2187209700}}
      testclass1 = TestClass1.new(var_2187229000)
      testclass2 = TestClass2.new("This is message 2", nil)
      @fixture = TestClass3.new(testclass1, testclass2)
    end

    it 'should pass current expectations' do
      # TestClass3#show_messages  should return awesome!!!
      expect( @fixture.show_messages ).to eq("awesome!!!")

    end
  end

  context 'Scenario 2' do
    before do
      var_2187209700 = TestClass1.new("test")
      var_2187229000 = {hello: "world", test: var_2187209700, arr_1: [1, 2, 3, 4, 5, var_2187209700], sub_hash: {yes: true, obj: var_2187209700}}
      testclass1 = TestClass1.new(var_2187229000)
      testclass2 = TestClass2.new("This is message 2", nil)
      @fixture = TestClass3.new(testclass1, testclass2)
    end

    it 'should pass current expectations' do
      # TestClass3#show_messages  should return awesome!!!
      expect( @fixture.show_messages ).to eq("awesome!!!")

    end
  end

end
